DELETE FROM user_events;
DELETE FROM alarms;
DELETE FROM app_errs;
DELETE FROM app_memos;
DELETE FROM arp_logs;
DELETE FROM db_errs;
DELETE FROM host_service_logs;
DELETE FROM host_service_noalarms;
DELETE FROM mactab;
DELETE FROM mactab_logs;
UPDATE host_services SET
	host_service_state = 'unknown',
	soft_state = 'unknown',
	hard_state = 'unknown',
	state_msg = NULL,
	check_attempts = 0,
	last_changed = NULL,
	last_touched = NULL,
	act_alarm_log_id = NULL,
	last_alarm_log_id = NULL,
	last_noalarm_msg = NULL;
UPDATE service_vars SET
	service_var_value = NULL,
	raw_value = NULL,
	var_state = 'unknown',
	last_time = NULL;
	