

ERRCODE(EOK,         "O.K."            ,0)
ERRCODE(EPROGFAIL,   "General bug"     ,1)
ERRCOD( EUNKNOWN,    "Unknown error")
ERRCOD( REDEFERRSTR, "Redefined error message and code" )
ERRCOD( ESETTING,    "Settings error")
ERRCOD( ESTD,        "Runtime error (std::exception)" )
ERRCOD( ENOTFILE,    "File not found" )
ERRCOD( ENODIR,      "Directory not found" )
ERRCOD( EFOPEN,      "File open error" )
ERRCOD( EFIOCTL,     "File IOCTL error" )
ERRCOD( EPCRE,       "Invalid regexp " )
ERRCOD( ENOINDEX,    "Invalid index value" )
ERRCOD( ENONAME,     "Invalid name value"    )
ERRCOD( ENOTSUPP,    "Function is not supported")
ERRCOD( EFREAD,      "File read error"           )
ERRCOD( EFWRITE,     "File write error"              )
ERRCOD( EQUERY,      "Error in SQL query"    )
ERRCOD( EPARSE,      "Parser error"               )
ERRCOD( ESQLOPEN,    "Database open error"          )
ERRCOD( ENOIMPL,     "Feature has not been implemented"    )
ERRCOD( EIP,         "Invalid IP address"         )
ERRCOD( ESNMP,       "SNMP error"                    )
ERRCOD( EOID,        "Incorrect Object Identifier")
ERRCOD( ENOFIELD,    "Field is not found in table")
ERRCOD( EDBDATA,     "Database content error"      )
ERRCOD( EENUMVAL,    "Invalid enumeration vallue")
ERRCOD( EOUTRANGE,   "Value out off range.")
ERRCOD( ETO,         "Time out"                )
ERRCOD( EXML,        "XML error"                     )
ERRCOD( EPROCCRE,    "Process crashed")
ERRCOD( EPROCEXIT,   "Process exited")
ERRCOD( EPROCERR,    "Process error")
ERRCOD( EPROCMANYE,  "Process to many error")
ERRCOD( EDATA,       "Invalid data"                 )
ERRCOD( EFOUND,      "Data not found")
ERRCOD( AMBIGUOUS,   "Ambiguous")
ERRCOD( NOTODO,      "Nothing to do.")
ERRCOD( ENOENV,      "Environment variable not found.")
ERRCOD( ESOCKET,     "Communication (socket). error.")
